<template>
  <div class="card">

    <div class="card-header" :class="isGenerated ? 'generated' : 'not-generated'">
      <h3>Output </h3>
    </div>

    <div class="card-body">
      <div class="pb-3">{{message}}</div>
      <table class="table table-bordered">

        <thead>
          <tr>
            <th> j </th>
            <th class="table-bordered" v-for="(n, index) in testString" :key="n"> j = {{index+1}} </th>
          </tr>
        
          <tr class="table-bordered" v-for="(n, index) in testString" :key="n"> 
            <th>{{n}}</th>
            <th v-for="prod in outputMatrix[index]" :key="prod"> {{prod?.toString()}} </th>
          </tr>
        </thead>

      </table>
    </div>

  </div>
</template>

<script>
export default {
  computed: {
    message(){
      if(this.isGenerated){
        return 'The string is generated by this grammar'
      }
      return 'The string is NOT generated by this grammar'
    }
  }
}
</script>

<style>
  div.generated{
    background-color: rgb(139, 219, 152);
  }

  div.not-generated{
    background-color: rgb(219, 139, 139);
  }
</style>
