<template>
  <div class="flex flex-col sm:flex-row items-center h-full sm:rounded-b-md bg-custom-secondary">

    <div class="w-full"> 
      <div class="text-2xl p-3 font-semibold text-white underline">Result:</div>
      <div class="px-3 pb-3 text-gray-300"> - {{message}}</div>
    </div>

    <div class="w-full text-white">
      <table class="flex flex-col place-items-center">

        <div class="flex flex-col m-4 shadow-lg cursor-default">

          <div class="flex flex-row">

            <div class="flex flex-col">
              <div class="flex flex-auto w-full p-2 rounded-sm px-3 transition duration-200 hover:bg-custom-secondary-dark font-mono">
                j
              </div>
              <div class="flex flex-auto w-full p-2 rounded-sm px-3 transition duration-200 hover:bg-custom-secondary-dark font-mono"
              v-for="(n, i) in testString" :key="i">{{n}}</div>
            </div>

            <div class="flex flex-col" v-for="(n, i) in testString" :key="i">
              <div class="flex flex-auto w-full p-2 rounded-sm px-3 transition duration-200 hover:bg-custom-secondary-dark font-mono">{{i+1}}</div>
              <div class="flex flex-auto w-full p-2 rounded-sm px-3 transition duration-200 hover:bg-custom-secondary-dark font-mono"
              v-for="(prod, j) in outputMatrix" :key="prod"> 
                {{ (outputMatrix[j][i]?.toString().length>0) ? outputMatrix[j][i]?.toString() : '*'}}
                </div>
            </div>
          </div>

        </div>

      </table>
    </div>

  </div>
</template>

<script>
export default {
  data(){
    return {
      testString_local: '',
      outputMatrix_local: [],
      isGenerated_local: false
    }
  },

  methods: {
    updateData(testString, isGenerated, outputMatrix){
      this.isGenerated= isGenerated
      this.outputMatrix = outputMatrix
      this.testString = testString
    }
  },

  computed: {
    testString:{
      get(){return this.testString_local},
      set(newValue){this.testString_local = newValue}
    },
    outputMatrix:{
      get(){return this.outputMatrix_local},
      set(newValue){this.outputMatrix_local = newValue}
    },
    isGenerated:{
      get(){return this.isGenerated_local},
      set(newValue){this.isGenerated_local = newValue}
    },

    message(){
      if(this.isGenerated){
        return 'The string is generated by this grammar'
      }
      return 'The string is NOT generated by this grammar'
    },

  }
}
</script>

<style>
</style>
